kafka:
  application-id: 111
  brokers: 1111
  ssl:
    truststorePath: 2123
    keystorePath: 3213
    credstorePsw: 421321
tokenx:
  client-id: ${TOKEN_X_CLIENT_ID}
  private-key: ${TOKEN_X_PRIVATE_JWK}
  token-endpoint: ${TOKEN_X_TOKEN_ENDPOINT}
  jwks-url: ${TOKEN_X_JWKS_URI}
  issuer: ${TOKEN_X_ISSUER}