/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aap.ettersendelse

import org.junit.jupiter.api.Assertions
import kotlin.test.Test

class AppTest {
    @Test
    fun hello() {
        Assertions.assertTrue(true)
    }
}
